/**
 * Domyślne teksty statyczne stron publicznych (nawigacja, nagłówki, przyciski,
 * mikroteksty). To jest "kod źródłowy prawdy" - te wartości działają nawet
 * bez wpisu w site_settings. Panel admina (zakładka "Teksty") edytuje
 * nadpisania przechowywane w site_settings pod kluczem 'copy'; efektywny
 * tekst to deepMergeCopy(defaultCopy, nadpisania).
 *
 * Nowe literały tekstowe na stronach publicznych powinny trafiać tutaj,
 * a nie jako string wpisany bezpośrednio w JSX - patrz CLAUDE.md/pamięć
 * projektu o edytowalnych treściach.
 */
export const defaultCopy = {
  gallery: {
    open: 'Otwórz zdjęcie na pełnym ekranie',
    close: 'Zamknij podgląd',
    zoomIn: 'Przybliż zdjęcie',
    zoomOut: 'Oddal zdjęcie',
    previous: 'Poprzednie zdjęcie',
    next: 'Następne zdjęcie',
  },
  nav: {
    rowery: 'Rowery',
    ramy: 'Ramy',
    realizacje: 'Realizacje',
    serwis: 'Serwis',
    cta: 'Stwórz własny projekt',
    adminAria: 'Panel administracyjny',
    menuAria: 'Otwórz menu',
    homeAria: 'Rexor Bikes — strona główna',
    navigationAria: 'Nawigacja główna',
  },
  footer: {
    serwis: 'Serwis',
    realizacje: 'Realizacje',
    konfigurator: 'Konfigurator',
    regulamin: 'Regulamin',
    polityka: 'Polityka prywatności',
    kontakt: 'Kontakt',
    vatNote: 'Ceny brutto',
  },
  home: {
    eyebrow: 'Rexor bikes',
    heroTitle: 'Zbudowany dla Twojej trasy',
    heroSubtitle: 'Wybierz konstrukcję, dobierz komponenty i zobacz cenę projektu jeszcze przed rozmową z Rexor.',
    heroCta: 'Rozpocznij konfigurację',
    modelsEyebrow: 'Polecane modele',
    modelsTitle: 'Wybierz swoją bazę',
    modelsAllCta: 'Wszystkie rowery',
    modelsEmptyTitle: 'Brak polecanych modeli',
    modelsEmptyText: 'Obecnie nie ma polecanych modeli do wyświetlenia. Sprawdź wszystkie rowery w naszym katalogu.',
    comingSoonBadge: 'W przygotowaniu',
    priceSoon: 'Wkrótce',
    modelLearnMoreCta: 'Poznaj model',
    modelConfigureCta: 'Konfiguruj',
    modelDetailsCta: 'Szczegóły',
    serviceEyebrow: 'Serwis Rexor',
    serviceTitle: 'Opieka po pierwszym kilometrze',
    serviceText: 'Diagnostyka napędu, regulacja zawieszenia, hamulców i przeglądy okresowe. Zakres zawsze potwierdzamy przed rozpoczęciem prac.',
    serviceCta: 'Sprawdź serwis',
  },
  bikes: {
    eyebrow: 'Rowery Rexor',
    title: 'Trzy różne punkty wyjścia',
    cardDetailsCta: 'Opis',
    priceSoon: 'Cena w przygotowaniu',
    configureCta: 'Konfiguruj',
    askCta: 'Zapytaj',
  },
  category: {
    eyebrow: 'Kategoria',
    notFoundTitle: 'Nie znaleziono tej kategorii',
    backToAllCta: 'Zobacz wszystkie rowery',
    emptyModels: 'Ta kategoria nie ma jeszcze przypisanych modeli. Wkrótce się to zmieni.',
    electricDisclaimerTitle: 'Uwaga, zanim zobaczysz ofertę',
    electricDisclaimerText: 'Pojazdy w tej kategorii przekraczają moc i prędkość wspomagania definiujące rower elektryczny w obowiązujących przepisach, dlatego nie oferujemy ich jako rowerów elektrycznych. Zapoznaj się z lokalnymi przepisami dotyczącymi tego typu pojazdów lub skontaktuj się z nami przed zakupem.',
    electricDisclaimerAccept: 'Rozumiem, pokaż ofertę',
  },
  model: {
    breadcrumbHome: 'Rexor',
    breadcrumbBikes: 'Rowery',
    notFoundEyebrow: 'Rower',
    notFoundTitle: 'Nie znaleziono takiego modelu',
    backToAllCta: 'Zobacz wszystkie rowery',
    configureCta: 'Konfiguruj ten model',
    askCta: 'Zapytaj o dostępność',
    categoryLabelPrefix: 'Kategoria:',
    startPriceLabel: 'Cena wyjściowa',
    priceSoon: 'Wycena w przygotowaniu',
    priceNote: 'Cena brutto wyliczana z sumy ramy, wybranego napędu, baterii, części domyślnych i montażu.',
    descriptionEyebrow: 'Opis i specyfikacja',
    expandDescriptionCta: 'Rozwiń',
    collapseDescriptionCta: 'Zwiń',
    descriptionTitlePrefix: 'Poznaj',
    bannerEyebrow: 'Konfigurator Rexor',
    bannerTitlePrefix: 'Zbuduj swój',
    bannerText: 'Wybierz rozmiar, osprzęt, baterię i dodatki pod swój styl jazdy oraz planowane trasy.',
  },
  frames: {
    eyebrow: 'Ramy',
    title: 'Geometria decyduje o charakterze',
    subtitle: 'Karbonowe i aluminiowe ramy, które sprzedajemy osobno - z pełną geometrią i naszą rekomendacją.',
    empty: 'Nie ma jeszcze opublikowanych ram. Napisz do nas, a sprawdzimy dostępność u producenta.',
    cardDetailsCta: 'Sprawdź szczegóły',
    recommendedBadge: 'Nasza rekomendacja',
    quotePrice: 'Wycena indywidualna',
    /** Informacja, że rama jest też pozycją samodzielną - właściciel prosił, żeby było to widoczne na liście. */
    frameOnlyTitle: 'Sama rama też jest w ofercie',
    frameOnlyText: 'Ramę możesz kupić osobno, bez budowy całego roweru. Możemy ją również polakierować według Twojego projektu - dowolny kolor, wzór albo odcień z palety samochodowej.',
    notFoundEyebrow: 'Rama',
    notFoundTitle: 'Nie znaleziono takiej ramy',
    backToAllCta: 'Zobacz wszystkie ramy',
    breadcrumbHome: 'Rexor',
    breadcrumbFrames: 'Ramy',
    manufacturerLabel: 'Producent',
    priceLabel: 'Cena ramy',
    priceNote: 'Cena brutto za samą ramę. Lakierowanie i montaż wyceniamy osobno.',
    descriptionTitle: 'Opis ramy',
    geometryTitle: 'Geometria',
    geometryEmpty: 'Geometria tej ramy jest w przygotowaniu. Napisz do nas, prześlemy tabelę producenta.',
    paintBadge: 'Lakierowanie wg projektu',
    paintSectionTitle: 'Kolory lakieru',
    paintSectionText: 'Ramę lakierujemy w kolorze z naszej palety albo w dowolnym odcieniu z palet samochodowych Porsche i Volkswagen. Podstrona ramy służy do obejrzenia kolorów - zakres lakierowania i cenę ustalamy w rozmowie.',
    paintBrowseCta: 'Przeglądaj kolory',
    paintBrowseLoading: 'Wczytuję kolory…',
    paintBrowseEmpty: 'Dla tej ramy nie włączono jeszcze palet kolorów. Napisz do nas - kolor ustalimy indywidualnie.',
    paintBrowseDialogTitle: 'Kolory dla tej ramy',
    sourceLinkLabel: 'Strona producenta',    formTitle: 'Zapytaj o tę ramę',
    formDescription: 'Napisz, jaki rozmiar i kolor Cię interesuje. Odpowiemy z terminem i ceną.',
    formSizeLabel: 'Rozmiar (opcjonalnie)',
    formPaintLabel: 'Kolor lakieru (opcjonalnie)',
  },
  projects: {
    eyebrow: 'Realizacje',
    title: 'Rowery, które już jeżdżą',
    subtitle: 'Prawdziwe realizacje zbudowane w Rexor - ze zdjęciami i pełnym spisem komponentów.',
    empty: 'Nie opublikowaliśmy jeszcze żadnej realizacji. Wkrótce się to zmieni.',
    cardDetailsCta: 'Zobacz realizację',
    completedPrefix: 'Ukończono',
    notFoundEyebrow: 'Realizacja',
    notFoundTitle: 'Nie znaleziono takiej realizacji',
    backToAllCta: 'Zobacz wszystkie realizacje',
    breadcrumbHome: 'Rexor',
    breadcrumbProjects: 'Realizacje',
    descriptionTitle: 'Jak powstał ten rower',
    specificationTitle: 'Specyfikacja',
    specificationLabelHeader: 'Element',
    specificationValueHeader: 'Zastosowany komponent',
    ctaTitle: 'Chcesz podobny rower?',
    ctaText: 'Zbuduj własny projekt w konfiguratorze albo napisz do nas - dobierzemy skład pod Twoje trasy.',
    ctaButton: 'Przejdź do konfiguratora',
  },
  /** Wspólne etykiety listy z filtrami kategorii (/ramy i /realizacje). */
  collection: {
    allFilter: 'Wszystkie',
    filtersAria: 'Filtr kategorii',
  },
  parts: {
    eyebrow: 'Części',
    title: 'Wybory, które naprawdę zmieniają jazdę',
    cta: 'Dobierz części w konfiguratorze',
    groups: {
      drive: { name: 'Napęd elektryczny', text: 'Silniki przypisane do ramy, wyświetlacze i ładowarki.' },
      suspension: { name: 'Zawieszenie', text: 'Widelce i dampery w wymiarach zgodnych z geometrią.' },
      brakes: { name: 'Hamulce', text: 'Czterotłoczkowe zestawy i dopasowane tarcze.' },
      mechDrive: { name: 'Napęd mechaniczny', text: 'Deore, CUES i Linkglide przygotowane do obciążeń e-MTB.' },
      wheels: { name: 'Koła i opony', text: 'Koła Boost oraz ogumienie dobrane do terenu.' },
      cockpit: { name: 'Kokpit', text: 'Kierownice, mostki, gripy, sztyce i punkty kontaktu.' },
    },
  },
  service: {
    eyebrow: 'Serwis Rexor',
    title: 'Pewność przed kolejną trasą',
    subtitle: 'Diagnostyka, regulacja i opieka nad rowerem przed sezonem oraz po wymagających kilometrach.',
    asideTitle: 'Zgłoś rower',
    asideText: 'Opisz model i objawy. Wrócimy z proponowanym terminem oraz zakresem.',
    asideCta: 'Napisz do serwisu',
    asideNote: 'Termin potwierdzamy indywidualnie',
  },
  content: {
    notPublished: 'Strona jest w przygotowaniu.',
    loading: 'Wczytuję…',
  },
  /** Wspólny formularz kontaktowy (/kontakt, /serwis, zapytanie o ramę). */
  contact: {
    asideTitle: 'Napisz do nas',
    asideDescription: 'Odpowiemy najszybciej, jak to możliwe.',
    nameLabel: 'Imię i nazwisko',
    emailLabel: 'E-mail',
    phoneLabel: 'Telefon (opcjonalnie)',
    messageLabel: 'Wiadomość',
    selectPlaceholder: 'Wybierz…',
    submitCta: 'Wyślij wiadomość',
    successTitle: 'Dziękujemy za wiadomość!',
    successText: 'Odpowiemy najszybciej, jak to możliwe.',
    submitError: 'Nie udało się wysłać wiadomości.',
  },
  /** Pływający doradca AI - opisy i etykiety okna; prompt asystenta edytuje
   *  się osobno w panelu (site_settings, zakładka czatu). */
  chat: {
    launcherAriaOpen: 'Otwórz czat z doradcą Rexor AI',
    launcherAriaClose: 'Zamknij czat z doradcą',
    badgeTitle: 'Doradca Rexor AI',
    teaser: 'Masz pytania o E82, E55, baterie lub zasięg? Kliknij tutaj!',
    teaserCloseAria: 'Zamknij podpowiedź',
    windowTitle: 'Doradca Rexor',
    onlineLabel: 'Online',
    windowSubtitle: 'Specyfikacje, baterie, zasięgi i cennik',
    clearTitle: 'Wyczyść rozmowę',
    closeTitle: 'Zamknij czat',
    analyzing: 'Rexor analizuje specyfikację...',
    inputPlaceholder: 'Zadaj pytanie o Rexor E82, E55, zasięg, cennik...',
    sendAria: 'Wyślij wiadomość',
    inputHint: 'Enter = wyślij, Shift + Enter = nowa linia',
    footer: 'Rexor Bikes • Custom e-MTB',
    greeting: 'Cześć! Jestem **Doradcą Rexor** 🚴‍♂️\n\nZnam pełne specyfikacje naszych maszyn, geometrie, silniki Bafang M560 i M620, pakiety akumulatorowe (982 Wh i 1310 Wh), zasięgi w kilometrach oraz aktualne cenniki i możliwości konfiguratora.\n\nO co chciałbyś zapytać?',
    noReplyError: 'Brak odpowiedzi od asystenta.',
    genericError: 'Wystąpił problem z połączeniem.',
  },
  configurator: {
    heroEyebrow: 'Wybierz bazę projektu',
    heroTitleLine1: 'Rower skrojony',
    heroTitleLine2: 'pod Twój teren.',
    heroSubtitle: 'Dobieraj komponenty, obserwuj cenę i wróć do swojego projektu przez prywatny link.',
    currentModelEyebrow: 'Konfigurujesz',
    changeModelCta: 'Zmień model',
    priceComingSoon: 'cena w przygotowaniu',
    aboutModelPrefix: 'O modelu',
    projectEyebrow: 'Twój projekt',
    configTitlePrefix: 'Konfiguracja',
    grossBadge: 'Brutto',
    unavailableTitle: 'Konfiguracja w przygotowaniu',
    unavailableText: 'Geometria i zdjęcia CFR707 są już gotowe. Uzupełniamy konkretne komponenty oraz cenę modelu.',
    unavailableCta: 'Zapytaj o CFR707',
    sizeSectionTitle: 'Rozmiar ramy',
    sizeSectionSubtitle: 'Dopasowanie potwierdzimy przed zamówieniem.',
    batterySectionTitle: 'Bateria',
    batterySectionSubtitle: 'Pakiet dobrany do ramy i silnika. Pojemność zmienia zasięg i masę roweru.',
    defaultBadge: 'W standardzie',
    includedPrice: 'w cenie',
    rangeEstimateTitle: 'Szacowane zasięgi',
    rangeEstimateSubtitle: 'Wyliczone na żywo w oparciu o typowe zużycie energii w zróżnicowanych warunkach.',
    rangeTableModeHeader: 'Tryb / warunki',
    rangeTableConsumptionHeader: 'Typowe zużycie',
    rangeTableRangeHeader: 'Estymowany zasięg',
    customerPartBadge: 'Twoja część',
    quotePrice: 'wycena',
    priceLabel: 'Sugerowana cena twojej konfiguracji',
    priceIndividual: 'wycena indywidualna',
    saveCta: 'Zapisz i przejdź do podsumowania',
    grossPriceNote: 'Cena brutto · zgodność potwierdzi Rexor',
    noneOptionName: 'Bez dodatku',
    noneOptionDetail: 'Nie dodawaj tego elementu.',
    customerPartDetail: 'Zgodność potwierdzi Rexor',
    saveDialogTitlePrefix: 'Zapisz projekt',
    saveDialogDescription: 'Podaj kontakt. Utworzymy prywatny link z dokładnie tą konfiguracją i przygotujemy wiadomość e-mail.',
    nameLabel: 'Imię i nazwisko',
    emailLabel: 'E-mail',
    phoneLabel: 'Telefon',
    optionalHint: '(opcjonalnie)',
    notesLabel: 'Uwagi',
    notesPlaceholder: 'Wzrost, styl jazdy lub inne istotne informacje',
    privacyConsentLabel: 'Zgadzam się na kontakt w sprawie tej konfiguracji i przetwarzanie podanych danych.',
    submittingCta: 'Zapisuję…',
    submitCta: 'Utwórz prywatny link',
    zoomedImageTitle: 'Powiększone zdjęcie części',
    resumeError: 'Nie udało się odtworzyć zapisanej konfiguracji.',
    privacyRequiredError: 'Zaznacz zgodę na kontakt i przetwarzanie danych.',
    submitError: 'Nie udało się zapisać konfiguracji.',
  },
  summary: {
    errorTitle: 'Nie możemy otworzyć projektu',
    backCta: 'Wróć do konfiguratora',
    loadingText: 'Otwieram zapisaną konfigurację…',
    savedEyebrow: 'Projekt zapisany',
    titleSuffix: 'w Twojej wersji',
    copyLinkCta: 'Kopiuj link',
    copiedCta: 'Skopiowano',
    emailShareCta: 'Wyślij e-mailem',
    emailSubjectPrefix: 'Konfiguracja',
    privacyNote: 'Link jest prywatny — zachowaj go, aby wrócić do podsumowania. Rexor potwierdzi kompatybilność i ostateczny zakres przed realizacją.',
    newProjectCta: 'Utwórz kolejny projekt',
    genericLoadError: 'Nie udało się otworzyć konfiguracji.',
  },
  snapshot: {
    projectNumberLabel: 'Numer projektu',
    grossPriceLabel: 'Cena brutto',
    sizeLabel: 'Rozmiar',
    batteryLabel: 'Bateria',
    selectedItemsTitle: 'Wybrane elementy',
    priceBreakdownTitle: 'Składniki ceny',
    frameAndSizeLabel: 'Rama i rozmiar',
    batteryLineLabel: 'Bateria',
    componentsLabel: 'Wybrane części',
    assemblyLabel: 'Składanie',
    marginLabelPrefix: 'Narzut',
    totalGrossLabel: 'Razem brutto',
    customerNotesTitle: 'Uwagi do zamówienia',
  },
  meta: {
    title: 'Konfigurator rowerów | Rexor Bikes',
    description: 'Zbuduj własny rower Rexor i zapisz konfigurację do późniejszego powrotu.',
  },
};

export type SiteCopy = typeof defaultCopy;

// Overrides z panelu admina są zwykle niepełne (obiekt częściowy) - użytkownik
// mógł edytować tylko część pól albo wpis w site_settings jeszcze nie istnieje.
type DeepPartial<T> = T extends string[] | string ? T : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> } : T;

export function mergeCopy(overrides: DeepPartial<SiteCopy> | null | undefined): SiteCopy {
  return deepMerge(defaultCopy, overrides ?? {}) as SiteCopy;
}

function deepMerge<T>(base: T, override: unknown): T {
  if (Array.isArray(base)) return (Array.isArray(override) ? override : base) as T;
  if (base && typeof base === 'object') {
    const result: Record<string, unknown> = { ...(base as Record<string, unknown>) };
    const overrideObj = (override && typeof override === 'object' && !Array.isArray(override)) ? (override as Record<string, unknown>) : {};
    for (const key of Object.keys(result)) {
      result[key] = deepMerge(result[key], overrideObj[key]);
      // Nagłówki bez końcowych kropek, także przy treści z panelu.
      if ((key === 'title' || key.endsWith('Title') || key === 'titleSuffix') && typeof result[key] === 'string') {
        result[key] = (result[key] as string).replace(/\.+\s*$/, '');
      }
    }
    return result as T;
  }
  return (override !== undefined && override !== null ? override : base) as T;
}
